var sfHome = require('./home/')
var sfGame = require('./game/')
var sfGameFinish = require('./game/finish/');
var sfForm = require('./form/')
var sfFormLink = require('./form/link/');
var sfLobby = require('./lobby/');
var sfSample = require('./sample/');
var sfMyactivity = require('./myactivity/');
var sfLink = require('./link/');
var sfCommon = require('./../common/');
var sfConstants = require('./../common/constants');

angular.module('quill-writer', [
    'ui.router',
    require('../../.tmp/config').name,
    require('../../.tmp/templates').name,

    // features
    sfHome,
    sfGame,
    sfGameFinish,
    sfLobby,
    sfSample,
    sfLink,
    sfMyactivity,

    // admin features
    sfForm,
    sfFormLink,

    // common, including components and services
    sfCommon,
    sfConstants,
    // third party modules
    // These will not be browserified
    'firebase',
    //'ui.bootstrap',
    'mgcrea.ngStrap',
    'underscore',
    'LocalStorageModule',
    'angulartics',
    'angulartics.mixpanel',
    'uuid4',
    'ngClipboard',
  ])

  .config(function($stateProvider, $urlRouterProvider, ngClipProvider, $locationProvider) {
    $urlRouterProvider.otherwise('/');

    // Enable HTML5 mode so that URLs generated by the LMS can be loaded in the iframe.
    $locationProvider.html5Mode({
      enabled: true
    });

    $stateProvider
      .state('sf', {
        abstract: true,
        views: {
          'header': {
            templateUrl: 'header.html'
          },
          'content': {
            template: '<div>Main Content</div>'
          },
          'footer': {
            template: 'footer.html'
          }
        }
      });
    ngClipProvider.setPath("//cdnjs.cloudflare.com/ajax/libs/zeroclipboard/2.1.6/ZeroClipboard.swf");

  })

;
